flowchart LR
    Piracicaba([Piracicaba]) --- |30| Americana([Americana])
    Americana([Americana]) --- |18| Sumare([Sumaré])
    Sumare([Sumaré]) --- |23| Campinas([Campinas])
    Campinas([Campinas]) --- |20| Indaiatuba([Indaiatuba])
    Indaiatuba([Indaiatuba]) --- |20| Salto([Salto])
    Salto([Salto]) --- |10| Itu([Itú])
    Itu([Itú]) --- |8| Sorocaba([Sorocaba])
    Sorocaba([Sorocaba]) --- |23| Boituva([Boituva])
    Boituva([Boituva]) --- |12| PortoFeliz([Porto Feliz])
